import { ThemeConfig } from '../types';

export const THEMES: ThemeConfig[] = [
  {
    id: 'light',
    name: 'Light Mode',
    description: 'Crisp clean interface with high contrast, pure whites, and royal indigo accents.',
    primary: 'bg-indigo-600 hover:bg-indigo-700 text-white',
    primaryHover: 'hover:bg-indigo-700',
    primaryText: 'text-indigo-600',
    bgPage: 'bg-[#f8fafc] text-slate-900',
    surfaceCard: 'bg-white border-slate-200/90 shadow-xs',
    surfaceCardHover: 'hover:border-slate-300',
    borderSubtle: 'border-slate-200',
    borderStrong: 'border-slate-300',
    textHeading: 'text-slate-900',
    textBody: 'text-slate-700',
    textMuted: 'text-slate-500',
    inputBg: 'bg-white text-slate-900 placeholder:text-slate-400',
    inputBorder: 'border-slate-300 focus:border-indigo-600 focus:ring-indigo-500/20',
    chatBubbleSender: 'bg-indigo-600 text-white',
    chatBubbleSenderText: 'text-white',
    chatBubbleReceiver: 'bg-slate-100 text-slate-900 border border-slate-200/80',
    chatBubbleReceiverText: 'text-slate-800',
    accentCodeColor: 'text-indigo-600',
    badgeBg: 'bg-indigo-50 text-indigo-700 border-indigo-200',
    badgeText: 'text-indigo-700',
  },
  {
    id: 'dark',
    name: 'Dark Mode',
    description: 'Deep midnight dark aesthetic with glowing indigo highlights and eye-safe surfaces.',
    primary: 'bg-indigo-600 hover:bg-indigo-500 text-white',
    primaryHover: 'hover:bg-indigo-500',
    primaryText: 'text-indigo-400',
    bgPage: 'bg-[#0b0f19] text-slate-100',
    surfaceCard: 'bg-[#151b28] border-slate-800/80 shadow-md',
    surfaceCardHover: 'hover:border-slate-700',
    borderSubtle: 'border-slate-800',
    borderStrong: 'border-slate-700',
    textHeading: 'text-white',
    textBody: 'text-slate-300',
    textMuted: 'text-slate-400',
    inputBg: 'bg-[#0f1422] text-white placeholder:text-slate-500',
    inputBorder: 'border-slate-700 focus:border-indigo-500 focus:ring-indigo-500/20',
    chatBubbleSender: 'bg-indigo-600 text-white',
    chatBubbleSenderText: 'text-white',
    chatBubbleReceiver: 'bg-[#1f2738] text-slate-100 border border-slate-700/60',
    chatBubbleReceiverText: 'text-slate-100',
    accentCodeColor: 'text-indigo-400',
    badgeBg: 'bg-indigo-950/80 text-indigo-300 border-indigo-800',
    badgeText: 'text-indigo-300',
  }
];

export const DEFAULT_THEME = THEMES[1]; // Default to dark mode or user preference
